repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: local
    hooks:
      - id: prettier
        name: Format HTML with Prettier
        entry: pixi run prettier --write
        language: system
        files: '\.(html|css|js|json|md|yaml|yml)$'