[workspace]
channels = ["conda-forge"]
name = "menu-bar"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run --all-files"

[dependencies]
pre-commit = ">=4.6.2,<5"
nodejs = ">=26.8.1,<26.9"
prettier = ">=3.9.6,<4"
